-- Menampilkan jumlah penggunaan masing-masing tipe pembayaran secara all time diurutkan dari yang terfavorit 
SELECT P.PAYMENT_TYPE, COUNT(O.ORDER_ID) TOTAL_ORDER
FROM ORDERS_DATASET O LEFT JOIN ORDER_PAYMENTS_DATASET P ON O.ORDER_ID = P.ORDER_ID 
GROUP BY P.PAYMENT_TYPE ORDER BY TOTAL_ORDER DESC ;

-- Menampilkan detail informasi jumlah penggunaan masing-masing tipe pembayaran untuk setiap tahun 
WITH AGG AS (SELECT DATE_PART('YEAR', ORDER_PURCHASE_TIMESTAMP) ACTIVE_YEAR, P.PAYMENT_TYPE, COUNT(O.ORDER_ID) TOTAL_ORDER
FROM ORDERS_DATASET O LEFT JOIN ORDER_PAYMENTS_DATASET P ON O.ORDER_ID = P.ORDER_ID 
WHERE P.PAYMENT_TYPE IS NOT NULL GROUP BY P.PAYMENT_TYPE, ACTIVE_YEAR)

SELECT PAYMENT_TYPE, 
	SUM(CASE WHEN ACTIVE_YEAR = 2016 THEN TOTAL_ORDER ELSE 0 END) AS "2016",
	SUM(CASE WHEN ACTIVE_YEAR = 2017 THEN TOTAL_ORDER ELSE 0 END) AS "2017",
	SUM(CASE WHEN ACTIVE_YEAR = 2018 THEN TOTAL_ORDER ELSE 0 END) AS "2018",
	SUM(TOTAL_ORDER) TOTAL_ORDER
	FROM AGG GROUP BY PAYMENT_TYPE ORDER BY 4 DESC;	